export interface IPrestamos{
    idoficina_principal: string,
    idprestamo: number,
    idcliente: string,
    idtipo_prestamo: string,
    monto_prestamo: string,
    tasa_interes: string,
    fecha_prestamo: string,
    fecha_desembolso: string,
    plazo: string,
    idsector_economico: string,
    fecha_vencimiento: string,
    monto_seguro_pagado: string,
    fecha_ultimo_calculo: string,
    monto_interes_calculado: string,
    monto_intereses_fin_mes: string,
    monto_pago_anticipado: string,
    valor_cuota: string,
    consecutivo_cuota: string,
    balance_corte: string,
    balance_prestamo: string,
    descripcion: string,
    act: string
}